/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface PagedResult {
    data: Array<ProposalDetail>;
    count: bigint;
    totalCount: bigint;
    offset: bigint;
}
export type Time = bigint;
export interface ICRC16Property {
    value: ICRC16;
    name: string;
    immutable: boolean;
}
export type ProposalKind = {
    __kind__: "setPdsCanister";
    setPdsCanister: ProposalData__1;
} | {
    __kind__: "postToBluesky";
    postToBluesky: ProposalData;
};
export interface ProposalData {
    message: string;
}
export interface DaoInterface {
    addMember(id: Principal): Promise<Result>;
    addWasmChunk(request: AddWasmChunkRequest): Promise<Result>;
    createProposal(proposal: ProposalKind): Promise<Result_1>;
    finalizeWasmChunks(wasmHash: Uint8Array): Promise<Result>;
    getMember(id: Principal): Promise<Member | null>;
    getMembers(): Promise<Array<Member>>;
    getPdsCanisterId(): Promise<Principal | null>;
    getProposal(proposalId: bigint): Promise<ProposalDetail | null>;
    getProposals(count: bigint, offset: bigint): Promise<PagedResult>;
    getVote(proposalId: bigint, voterId: Principal): Promise<Vote | null>;
    getWasmHashes(): Promise<Array<string>>;
    icrc120_get_events(input: {
        prev?: Uint8Array;
        take?: bigint;
        filter?: GetEventsFilter;
    }): Promise<Array<OrchestrationEvent>>;
    removeMember(id: Principal): Promise<Result>;
    vote(proposalId: bigint, vote: boolean): Promise<Result>;
}
export interface InstallOptions {
    initArgs: {
        __kind__: "raw";
        raw: Uint8Array;
    } | {
        __kind__: "candidText";
        candidText: string;
    };
    wasmHash: Uint8Array;
    kind: Variant_reinstall_upgrade_install;
}
export interface OrchestrationEvent {
    id: bigint;
    canister_id: Principal;
    timestamp: bigint;
    details: ICRC16;
    event_type: OrchestrationEventType;
}
export type Result_1 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface GetEventsFilter {
    event_types?: Array<OrchestrationEventType>;
    end_time?: bigint;
    start_time?: bigint;
    canister?: Principal;
}
export type ProposalStatus = {
    __kind__: "failedToExecute";
    failedToExecute: {
        executingTime: Time;
        error: string;
        failedTime: Time;
        choice?: boolean;
    };
} | {
    __kind__: "open";
    open: null;
} | {
    __kind__: "executing";
    executing: {
        executingTime: Time;
        choice?: boolean;
    };
} | {
    __kind__: "executed";
    executed: {
        executingTime: Time;
        choice?: boolean;
        executedTime: Time;
    };
};
export interface ProposalDetail {
    id: bigint;
    status: ProposalStatus;
    title: string;
    votesAgainst: bigint;
    timeStart: bigint;
    votesFor: bigint;
    totalVotingPower: bigint;
    description: string;
    timeEnd?: bigint;
}
export interface ProposalData__1 {
    kind: {
        __kind__: "set";
        set: null;
    } | {
        __kind__: "install";
        install: InstallOptions;
    };
    canisterId: Principal;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface AddWasmChunkRequest {
    wasmHash: Uint8Array;
    chunk: Uint8Array;
    index: bigint;
}
export interface Member {
    id: Principal;
    votingPower: bigint;
}
export type ICRC16 = {
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Map";
    Map: Array<[string, ICRC16]>;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Set";
    Set: Array<ICRC16>;
} | {
    __kind__: "Nat16";
    Nat16: number;
} | {
    __kind__: "Nat32";
    Nat32: number;
} | {
    __kind__: "Nat64";
    Nat64: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Bool";
    Bool: boolean;
} | {
    __kind__: "Int8";
    Int8: number;
} | {
    __kind__: "Nat8";
    Nat8: number;
} | {
    __kind__: "Nats";
    Nats: Array<bigint>;
} | {
    __kind__: "Text";
    Text: string;
} | {
    __kind__: "Bytes";
    Bytes: Uint8Array;
} | {
    __kind__: "Int16";
    Int16: number;
} | {
    __kind__: "Int32";
    Int32: number;
} | {
    __kind__: "Int64";
    Int64: bigint;
} | {
    __kind__: "Option";
    Option: ICRC16 | null;
} | {
    __kind__: "Floats";
    Floats: Array<number>;
} | {
    __kind__: "Float";
    Float: number;
} | {
    __kind__: "Principal";
    Principal: Principal;
} | {
    __kind__: "Array";
    Array: Array<ICRC16>;
} | {
    __kind__: "ValueMap";
    ValueMap: Array<[ICRC16, ICRC16]>;
} | {
    __kind__: "Class";
    Class: Array<ICRC16Property>;
};
export interface Vote {
    votingPower: bigint;
    choice?: boolean;
}
export enum OrchestrationEventType {
    upgrade_initiated = "upgrade_initiated",
    snapshot_requested = "snapshot_requested",
    snapshot_revert_requested = "snapshot_revert_requested",
    snapshot_cleaned = "snapshot_cleaned",
    upgrade_finished = "upgrade_finished",
    configuration_changed = "configuration_changed",
    snapshot_reverted = "snapshot_reverted",
    canister_started = "canister_started",
    snapshot_created = "snapshot_created",
    canister_stopped = "canister_stopped"
}
export enum Variant_reinstall_upgrade_install {
    reinstall = "reinstall",
    upgrade = "upgrade",
    install = "install"
}
export interface backendInterface extends DaoInterface {
}
import type { GetEventsFilter as _GetEventsFilter, ICRC16 as _ICRC16, ICRC16Property as _ICRC16Property, InstallOptions as _InstallOptions, Member as _Member, OrchestrationEvent as _OrchestrationEvent, OrchestrationEventType as _OrchestrationEventType, PagedResult as _PagedResult, ProposalData as _ProposalData, ProposalData__1 as _ProposalData__1, ProposalDetail as _ProposalDetail, ProposalKind as _ProposalKind, ProposalStatus as _ProposalStatus, Result as _Result, Result_1 as _Result_1, Time as _Time, Vote as _Vote } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async addMember(arg0: Principal): Promise<Result> {
        const result = await this.actor.addMember(arg0);
        return from_candid_Result_n1(result);
    }
    async addWasmChunk(arg0: AddWasmChunkRequest): Promise<Result> {
        const result = await this.actor.addWasmChunk(arg0);
        return from_candid_Result_n1(result);
    }
    async createProposal(arg0: ProposalKind): Promise<Result_1> {
        const result = await this.actor.createProposal(to_candid_ProposalKind_n3(arg0));
        return from_candid_Result_1_n12(result);
    }
    async finalizeWasmChunks(arg0: Uint8Array): Promise<Result> {
        const result = await this.actor.finalizeWasmChunks(arg0);
        return from_candid_Result_n1(result);
    }
    async getMember(arg0: Principal): Promise<Member | null> {
        const result = await this.actor.getMember(arg0);
        return from_candid_opt_n14(result);
    }
    async getMembers(): Promise<Array<Member>> {
        const result = await this.actor.getMembers();
        return result;
    }
    async getPdsCanisterId(): Promise<Principal | null> {
        const result = await this.actor.getPdsCanisterId();
        return from_candid_opt_n15(result);
    }
    async getProposal(arg0: bigint): Promise<ProposalDetail | null> {
        const result = await this.actor.getProposal(arg0);
        return from_candid_opt_n16(result);
    }
    async getProposals(arg0: bigint, arg1: bigint): Promise<PagedResult> {
        const result = await this.actor.getProposals(arg0, arg1);
        return from_candid_PagedResult_n26(result);
    }
    async getVote(arg0: bigint, arg1: Principal): Promise<Vote | null> {
        const result = await this.actor.getVote(arg0, arg1);
        return from_candid_opt_n29(result);
    }
    async getWasmHashes(): Promise<Array<string>> {
        const result = await this.actor.getWasmHashes();
        return result;
    }
    async icrc120_get_events(arg0: {
        prev?: Uint8Array;
        take?: bigint;
        filter?: GetEventsFilter;
    }): Promise<Array<OrchestrationEvent>> {
        const result = await this.actor.icrc120_get_events(to_candid_record_n32(arg0));
        return from_candid_vec_n38(result);
    }
    async removeMember(arg0: Principal): Promise<Result> {
        const result = await this.actor.removeMember(arg0);
        return from_candid_Result_n1(result);
    }
    async vote(arg0: bigint, arg1: boolean): Promise<Result> {
        const result = await this.actor.vote(arg0, arg1);
        return from_candid_Result_n1(result);
    }
}
function from_candid_ICRC16Property_n50(value: _ICRC16Property): ICRC16Property {
    return from_candid_record_n51(value);
}
function from_candid_ICRC16_n41(value: _ICRC16): ICRC16 {
    return from_candid_variant_n42(value);
}
function from_candid_OrchestrationEventType_n52(value: _OrchestrationEventType): OrchestrationEventType {
    return from_candid_variant_n53(value);
}
function from_candid_OrchestrationEvent_n39(value: _OrchestrationEvent): OrchestrationEvent {
    return from_candid_record_n40(value);
}
function from_candid_PagedResult_n26(value: _PagedResult): PagedResult {
    return from_candid_record_n27(value);
}
function from_candid_ProposalDetail_n17(value: _ProposalDetail): ProposalDetail {
    return from_candid_record_n18(value);
}
function from_candid_ProposalStatus_n19(value: _ProposalStatus): ProposalStatus {
    return from_candid_variant_n20(value);
}
function from_candid_Result_1_n12(value: _Result_1): Result_1 {
    return from_candid_variant_n13(value);
}
function from_candid_Result_n1(value: _Result): Result {
    return from_candid_variant_n2(value);
}
function from_candid_Vote_n30(value: _Vote): Vote {
    return from_candid_record_n31(value);
}
function from_candid_opt_n14(value: [] | [_Member]): Member | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(value: [] | [_ProposalDetail]): ProposalDetail | null {
    return value.length === 0 ? null : from_candid_ProposalDetail_n17(value[0]);
}
function from_candid_opt_n22(value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(value: [] | [_Vote]): Vote | null {
    return value.length === 0 ? null : from_candid_Vote_n30(value[0]);
}
function from_candid_opt_n46(value: [] | [_ICRC16]): ICRC16 | null {
    return value.length === 0 ? null : from_candid_ICRC16_n41(value[0]);
}
function from_candid_record_n18(value: {
    id: bigint;
    status: _ProposalStatus;
    title: string;
    votesAgainst: bigint;
    timeStart: bigint;
    votesFor: bigint;
    totalVotingPower: bigint;
    description: string;
    timeEnd: [] | [bigint];
}): {
    id: bigint;
    status: ProposalStatus;
    title: string;
    votesAgainst: bigint;
    timeStart: bigint;
    votesFor: bigint;
    totalVotingPower: bigint;
    description: string;
    timeEnd?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ProposalStatus_n19(value.status),
        title: value.title,
        votesAgainst: value.votesAgainst,
        timeStart: value.timeStart,
        votesFor: value.votesFor,
        totalVotingPower: value.totalVotingPower,
        description: value.description,
        timeEnd: record_opt_to_undefined(from_candid_opt_n25(value.timeEnd))
    };
}
function from_candid_record_n21(value: {
    executingTime: _Time;
    error: string;
    failedTime: _Time;
    choice: [] | [boolean];
}): {
    executingTime: Time;
    error: string;
    failedTime: Time;
    choice?: boolean;
} {
    return {
        executingTime: value.executingTime,
        error: value.error,
        failedTime: value.failedTime,
        choice: record_opt_to_undefined(from_candid_opt_n22(value.choice))
    };
}
function from_candid_record_n23(value: {
    executingTime: _Time;
    choice: [] | [boolean];
}): {
    executingTime: Time;
    choice?: boolean;
} {
    return {
        executingTime: value.executingTime,
        choice: record_opt_to_undefined(from_candid_opt_n22(value.choice))
    };
}
function from_candid_record_n24(value: {
    executingTime: _Time;
    choice: [] | [boolean];
    executedTime: _Time;
}): {
    executingTime: Time;
    choice?: boolean;
    executedTime: Time;
} {
    return {
        executingTime: value.executingTime,
        choice: record_opt_to_undefined(from_candid_opt_n22(value.choice)),
        executedTime: value.executedTime
    };
}
function from_candid_record_n27(value: {
    data: Array<_ProposalDetail>;
    count: bigint;
    totalCount: bigint;
    offset: bigint;
}): {
    data: Array<ProposalDetail>;
    count: bigint;
    totalCount: bigint;
    offset: bigint;
} {
    return {
        data: from_candid_vec_n28(value.data),
        count: value.count,
        totalCount: value.totalCount,
        offset: value.offset
    };
}
function from_candid_record_n31(value: {
    votingPower: bigint;
    choice: [] | [boolean];
}): {
    votingPower: bigint;
    choice?: boolean;
} {
    return {
        votingPower: value.votingPower,
        choice: record_opt_to_undefined(from_candid_opt_n22(value.choice))
    };
}
function from_candid_record_n40(value: {
    id: bigint;
    canister_id: Principal;
    timestamp: bigint;
    details: _ICRC16;
    event_type: _OrchestrationEventType;
}): {
    id: bigint;
    canister_id: Principal;
    timestamp: bigint;
    details: ICRC16;
    event_type: OrchestrationEventType;
} {
    return {
        id: value.id,
        canister_id: value.canister_id,
        timestamp: value.timestamp,
        details: from_candid_ICRC16_n41(value.details),
        event_type: from_candid_OrchestrationEventType_n52(value.event_type)
    };
}
function from_candid_record_n51(value: {
    value: _ICRC16;
    name: string;
    immutable: boolean;
}): {
    value: ICRC16;
    name: string;
    immutable: boolean;
} {
    return {
        value: from_candid_ICRC16_n41(value.value),
        name: value.name,
        immutable: value.immutable
    };
}
function from_candid_tuple_n44(value: [string, _ICRC16]): [string, ICRC16] {
    return [
        value[0],
        from_candid_ICRC16_n41(value[1])
    ];
}
function from_candid_tuple_n48(value: [_ICRC16, _ICRC16]): [ICRC16, ICRC16] {
    return [
        from_candid_ICRC16_n41(value[0]),
        from_candid_ICRC16_n41(value[1])
    ];
}
function from_candid_variant_n13(value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(value: {
    failedToExecute: {
        executingTime: _Time;
        error: string;
        failedTime: _Time;
        choice: [] | [boolean];
    };
} | {
    open: null;
} | {
    executing: {
        executingTime: _Time;
        choice: [] | [boolean];
    };
} | {
    executed: {
        executingTime: _Time;
        choice: [] | [boolean];
        executedTime: _Time;
    };
}): {
    __kind__: "failedToExecute";
    failedToExecute: {
        executingTime: Time;
        error: string;
        failedTime: Time;
        choice?: boolean;
    };
} | {
    __kind__: "open";
    open: null;
} | {
    __kind__: "executing";
    executing: {
        executingTime: Time;
        choice?: boolean;
    };
} | {
    __kind__: "executed";
    executed: {
        executingTime: Time;
        choice?: boolean;
        executedTime: Time;
    };
} {
    return "failedToExecute" in value ? {
        __kind__: "failedToExecute",
        failedToExecute: from_candid_record_n21(value.failedToExecute)
    } : "open" in value ? {
        __kind__: "open",
        open: value.open
    } : "executing" in value ? {
        __kind__: "executing",
        executing: from_candid_record_n23(value.executing)
    } : "executed" in value ? {
        __kind__: "executed",
        executed: from_candid_record_n24(value.executed)
    } : value;
}
function from_candid_variant_n42(value: {
    Int: bigint;
} | {
    Map: Array<[string, _ICRC16]>;
} | {
    Nat: bigint;
} | {
    Set: Array<_ICRC16>;
} | {
    Nat16: number;
} | {
    Nat32: number;
} | {
    Nat64: bigint;
} | {
    Blob: Uint8Array;
} | {
    Bool: boolean;
} | {
    Int8: number;
} | {
    Nat8: number;
} | {
    Nats: Array<bigint>;
} | {
    Text: string;
} | {
    Bytes: Uint8Array;
} | {
    Int16: number;
} | {
    Int32: number;
} | {
    Int64: bigint;
} | {
    Option: [] | [_ICRC16];
} | {
    Floats: Array<number>;
} | {
    Float: number;
} | {
    Principal: Principal;
} | {
    Array: Array<_ICRC16>;
} | {
    ValueMap: Array<[_ICRC16, _ICRC16]>;
} | {
    Class: Array<_ICRC16Property>;
}): {
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Map";
    Map: Array<[string, ICRC16]>;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Set";
    Set: Array<ICRC16>;
} | {
    __kind__: "Nat16";
    Nat16: number;
} | {
    __kind__: "Nat32";
    Nat32: number;
} | {
    __kind__: "Nat64";
    Nat64: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Bool";
    Bool: boolean;
} | {
    __kind__: "Int8";
    Int8: number;
} | {
    __kind__: "Nat8";
    Nat8: number;
} | {
    __kind__: "Nats";
    Nats: Array<bigint>;
} | {
    __kind__: "Text";
    Text: string;
} | {
    __kind__: "Bytes";
    Bytes: Uint8Array;
} | {
    __kind__: "Int16";
    Int16: number;
} | {
    __kind__: "Int32";
    Int32: number;
} | {
    __kind__: "Int64";
    Int64: bigint;
} | {
    __kind__: "Option";
    Option: ICRC16 | null;
} | {
    __kind__: "Floats";
    Floats: Array<number>;
} | {
    __kind__: "Float";
    Float: number;
} | {
    __kind__: "Principal";
    Principal: Principal;
} | {
    __kind__: "Array";
    Array: Array<ICRC16>;
} | {
    __kind__: "ValueMap";
    ValueMap: Array<[ICRC16, ICRC16]>;
} | {
    __kind__: "Class";
    Class: Array<ICRC16Property>;
} {
    return "Int" in value ? {
        __kind__: "Int",
        Int: value.Int
    } : "Map" in value ? {
        __kind__: "Map",
        Map: from_candid_vec_n43(value.Map)
    } : "Nat" in value ? {
        __kind__: "Nat",
        Nat: value.Nat
    } : "Set" in value ? {
        __kind__: "Set",
        Set: from_candid_vec_n45(value.Set)
    } : "Nat16" in value ? {
        __kind__: "Nat16",
        Nat16: value.Nat16
    } : "Nat32" in value ? {
        __kind__: "Nat32",
        Nat32: value.Nat32
    } : "Nat64" in value ? {
        __kind__: "Nat64",
        Nat64: value.Nat64
    } : "Blob" in value ? {
        __kind__: "Blob",
        Blob: value.Blob
    } : "Bool" in value ? {
        __kind__: "Bool",
        Bool: value.Bool
    } : "Int8" in value ? {
        __kind__: "Int8",
        Int8: value.Int8
    } : "Nat8" in value ? {
        __kind__: "Nat8",
        Nat8: value.Nat8
    } : "Nats" in value ? {
        __kind__: "Nats",
        Nats: value.Nats
    } : "Text" in value ? {
        __kind__: "Text",
        Text: value.Text
    } : "Bytes" in value ? {
        __kind__: "Bytes",
        Bytes: value.Bytes
    } : "Int16" in value ? {
        __kind__: "Int16",
        Int16: value.Int16
    } : "Int32" in value ? {
        __kind__: "Int32",
        Int32: value.Int32
    } : "Int64" in value ? {
        __kind__: "Int64",
        Int64: value.Int64
    } : "Option" in value ? {
        __kind__: "Option",
        Option: from_candid_opt_n46(value.Option)
    } : "Floats" in value ? {
        __kind__: "Floats",
        Floats: value.Floats
    } : "Float" in value ? {
        __kind__: "Float",
        Float: value.Float
    } : "Principal" in value ? {
        __kind__: "Principal",
        Principal: value.Principal
    } : "Array" in value ? {
        __kind__: "Array",
        Array: from_candid_vec_n45(value.Array)
    } : "ValueMap" in value ? {
        __kind__: "ValueMap",
        ValueMap: from_candid_vec_n47(value.ValueMap)
    } : "Class" in value ? {
        __kind__: "Class",
        Class: from_candid_vec_n49(value.Class)
    } : value;
}
function from_candid_variant_n53(value: {
    upgrade_initiated: null;
} | {
    snapshot_requested: null;
} | {
    snapshot_revert_requested: null;
} | {
    snapshot_cleaned: null;
} | {
    upgrade_finished: null;
} | {
    configuration_changed: null;
} | {
    snapshot_reverted: null;
} | {
    canister_started: null;
} | {
    snapshot_created: null;
} | {
    canister_stopped: null;
}): OrchestrationEventType {
    return "upgrade_initiated" in value ? OrchestrationEventType.upgrade_initiated : "snapshot_requested" in value ? OrchestrationEventType.snapshot_requested : "snapshot_revert_requested" in value ? OrchestrationEventType.snapshot_revert_requested : "snapshot_cleaned" in value ? OrchestrationEventType.snapshot_cleaned : "upgrade_finished" in value ? OrchestrationEventType.upgrade_finished : "configuration_changed" in value ? OrchestrationEventType.configuration_changed : "snapshot_reverted" in value ? OrchestrationEventType.snapshot_reverted : "canister_started" in value ? OrchestrationEventType.canister_started : "snapshot_created" in value ? OrchestrationEventType.snapshot_created : "canister_stopped" in value ? OrchestrationEventType.canister_stopped : value;
}
function from_candid_vec_n28(value: Array<_ProposalDetail>): Array<ProposalDetail> {
    return value.map((x)=>from_candid_ProposalDetail_n17(x));
}
function from_candid_vec_n38(value: Array<_OrchestrationEvent>): Array<OrchestrationEvent> {
    return value.map((x)=>from_candid_OrchestrationEvent_n39(x));
}
function from_candid_vec_n43(value: Array<[string, _ICRC16]>): Array<[string, ICRC16]> {
    return value.map((x)=>from_candid_tuple_n44(x));
}
function from_candid_vec_n45(value: Array<_ICRC16>): Array<ICRC16> {
    return value.map((x)=>from_candid_ICRC16_n41(x));
}
function from_candid_vec_n47(value: Array<[_ICRC16, _ICRC16]>): Array<[ICRC16, ICRC16]> {
    return value.map((x)=>from_candid_tuple_n48(x));
}
function from_candid_vec_n49(value: Array<_ICRC16Property>): Array<ICRC16Property> {
    return value.map((x)=>from_candid_ICRC16Property_n50(x));
}
function to_candid_GetEventsFilter_n33(value: GetEventsFilter): _GetEventsFilter {
    return to_candid_record_n34(value);
}
function to_candid_InstallOptions_n8(value: InstallOptions): _InstallOptions {
    return to_candid_record_n9(value);
}
function to_candid_OrchestrationEventType_n36(value: OrchestrationEventType): _OrchestrationEventType {
    return to_candid_variant_n37(value);
}
function to_candid_ProposalData__1_n5(value: ProposalData__1): _ProposalData__1 {
    return to_candid_record_n6(value);
}
function to_candid_ProposalKind_n3(value: ProposalKind): _ProposalKind {
    return to_candid_variant_n4(value);
}
function to_candid_record_n32(value: {
    prev?: Uint8Array;
    take?: bigint;
    filter?: GetEventsFilter;
}): {
    prev: [] | [Uint8Array];
    take: [] | [bigint];
    filter: [] | [_GetEventsFilter];
} {
    return {
        prev: value.prev ? candid_some(value.prev) : candid_none(),
        take: value.take ? candid_some(value.take) : candid_none(),
        filter: value.filter ? candid_some(to_candid_GetEventsFilter_n33(value.filter)) : candid_none()
    };
}
function to_candid_record_n34(value: {
    event_types?: Array<OrchestrationEventType>;
    end_time?: bigint;
    start_time?: bigint;
    canister?: Principal;
}): {
    event_types: [] | [Array<_OrchestrationEventType>];
    end_time: [] | [bigint];
    start_time: [] | [bigint];
    canister: [] | [Principal];
} {
    return {
        event_types: value.event_types ? candid_some(to_candid_vec_n35(value.event_types)) : candid_none(),
        end_time: value.end_time ? candid_some(value.end_time) : candid_none(),
        start_time: value.start_time ? candid_some(value.start_time) : candid_none(),
        canister: value.canister ? candid_some(value.canister) : candid_none()
    };
}
function to_candid_record_n6(value: {
    kind: {
        __kind__: "set";
        set: null;
    } | {
        __kind__: "install";
        install: InstallOptions;
    };
    canisterId: Principal;
}): {
    kind: {
        set: null;
    } | {
        install: _InstallOptions;
    };
    canisterId: Principal;
} {
    return {
        kind: to_candid_variant_n7(value.kind),
        canisterId: value.canisterId
    };
}
function to_candid_record_n9(value: {
    initArgs: {
        __kind__: "raw";
        raw: Uint8Array;
    } | {
        __kind__: "candidText";
        candidText: string;
    };
    wasmHash: Uint8Array;
    kind: Variant_reinstall_upgrade_install;
}): {
    initArgs: {
        raw: Uint8Array;
    } | {
        candidText: string;
    };
    wasmHash: Uint8Array;
    kind: {
        reinstall: null;
    } | {
        upgrade: null;
    } | {
        install: null;
    };
} {
    return {
        initArgs: to_candid_variant_n10(value.initArgs),
        wasmHash: value.wasmHash,
        kind: to_candid_variant_n11(value.kind)
    };
}
function to_candid_variant_n10(value: {
    __kind__: "raw";
    raw: Uint8Array;
} | {
    __kind__: "candidText";
    candidText: string;
}): {
    raw: Uint8Array;
} | {
    candidText: string;
} {
    return value.__kind__ === "raw" ? {
        raw: value.raw
    } : value.__kind__ === "candidText" ? {
        candidText: value.candidText
    } : value;
}
function to_candid_variant_n11(value: Variant_reinstall_upgrade_install): {
    reinstall: null;
} | {
    upgrade: null;
} | {
    install: null;
} {
    return value == Variant_reinstall_upgrade_install.reinstall ? {
        reinstall: null
    } : value == Variant_reinstall_upgrade_install.upgrade ? {
        upgrade: null
    } : value == Variant_reinstall_upgrade_install.install ? {
        install: null
    } : value;
}
function to_candid_variant_n37(value: OrchestrationEventType): {
    upgrade_initiated: null;
} | {
    snapshot_requested: null;
} | {
    snapshot_revert_requested: null;
} | {
    snapshot_cleaned: null;
} | {
    upgrade_finished: null;
} | {
    configuration_changed: null;
} | {
    snapshot_reverted: null;
} | {
    canister_started: null;
} | {
    snapshot_created: null;
} | {
    canister_stopped: null;
} {
    return value == OrchestrationEventType.upgrade_initiated ? {
        upgrade_initiated: null
    } : value == OrchestrationEventType.snapshot_requested ? {
        snapshot_requested: null
    } : value == OrchestrationEventType.snapshot_revert_requested ? {
        snapshot_revert_requested: null
    } : value == OrchestrationEventType.snapshot_cleaned ? {
        snapshot_cleaned: null
    } : value == OrchestrationEventType.upgrade_finished ? {
        upgrade_finished: null
    } : value == OrchestrationEventType.configuration_changed ? {
        configuration_changed: null
    } : value == OrchestrationEventType.snapshot_reverted ? {
        snapshot_reverted: null
    } : value == OrchestrationEventType.canister_started ? {
        canister_started: null
    } : value == OrchestrationEventType.snapshot_created ? {
        snapshot_created: null
    } : value == OrchestrationEventType.canister_stopped ? {
        canister_stopped: null
    } : value;
}
function to_candid_variant_n4(value: {
    __kind__: "setPdsCanister";
    setPdsCanister: ProposalData__1;
} | {
    __kind__: "postToBluesky";
    postToBluesky: ProposalData;
}): {
    setPdsCanister: _ProposalData__1;
} | {
    postToBluesky: _ProposalData;
} {
    return value.__kind__ === "setPdsCanister" ? {
        setPdsCanister: to_candid_ProposalData__1_n5(value.setPdsCanister)
    } : value.__kind__ === "postToBluesky" ? {
        postToBluesky: value.postToBluesky
    } : value;
}
function to_candid_variant_n7(value: {
    __kind__: "set";
    set: null;
} | {
    __kind__: "install";
    install: InstallOptions;
}): {
    set: null;
} | {
    install: _InstallOptions;
} {
    return value.__kind__ === "set" ? {
        set: value.set
    } : value.__kind__ === "install" ? {
        install: to_candid_InstallOptions_n8(value.install)
    } : value;
}
function to_candid_vec_n35(value: Array<OrchestrationEventType>): Array<_OrchestrationEventType> {
    return value.map((x)=>to_candid_OrchestrationEventType_n36(x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor);
}
