/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/dao_backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export interface PagedResult {
    data: Array<ProposalDetail>;
    count: bigint;
    totalCount: bigint;
    offset: bigint;
}
export type Time = bigint;
export type ProposalKind = {
    __kind__: "setPdsCanister";
    setPdsCanister: ProposalData__1;
} | {
    __kind__: "postToBluesky";
    postToBluesky: ProposalData;
};
export interface ProposalData {
    message: string;
}
export interface InstallAndInitializeOptions {
    initializeOptions: InitializeOptions;
    initArgs: Uint8Array;
    wasmModule: Uint8Array;
}
export interface InitializeOptions {
    hostname: string;
    serviceSubdomain?: string;
    plcIdentifier: string;
}
export interface DaoInterface {
    createProposal(proposal: ProposalKind): Promise<Result_1>;
    getMembers(): Promise<Array<Member>>;
    getPdsCanisterId(): Promise<Principal | null>;
    getProposal(proposalId: bigint): Promise<ProposalDetail | null>;
    getProposals(count: bigint, offset: bigint): Promise<PagedResult>;
    getVote(proposalId: bigint, voterId: Principal): Promise<Vote | null>;
    vote(proposalId: bigint, vote: boolean): Promise<Result>;
}
export type Result_1 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export type ProposalStatus = {
    __kind__: "failedToExecute";
    failedToExecute: {
        executingTime: Time;
        error: string;
        failedTime: Time;
        choice?: boolean;
    };
} | {
    __kind__: "open";
    open: null;
} | {
    __kind__: "executing";
    executing: {
        executingTime: Time;
        choice?: boolean;
    };
} | {
    __kind__: "executed";
    executed: {
        executingTime: Time;
        choice?: boolean;
        executedTime: Time;
    };
};
export interface ProposalDetail {
    id: bigint;
    status: ProposalStatus;
    title: string;
    votesAgainst: bigint;
    timeStart: bigint;
    votesFor: bigint;
    totalVotingPower: bigint;
    description: string;
    timeEnd?: bigint;
}
export interface ProposalData__1 {
    id: Principal;
    kind: {
        __kind__: "set";
        set: null;
    } | {
        __kind__: "installAndInitialize";
        installAndInitialize: InstallAndInitializeOptions;
    } | {
        __kind__: "initialize";
        initialize: InitializeOptions;
    };
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface Member {
    id: Principal;
    votingPower: bigint;
}
export interface Vote {
    votingPower: bigint;
    choice?: boolean;
}
export interface dao_backendInterface extends DaoInterface {
}
import type { InitializeOptions as _InitializeOptions, InstallAndInitializeOptions as _InstallAndInitializeOptions, PagedResult as _PagedResult, ProposalData as _ProposalData, ProposalData__1 as _ProposalData__1, ProposalDetail as _ProposalDetail, ProposalKind as _ProposalKind, ProposalStatus as _ProposalStatus, Result as _Result, Result_1 as _Result_1, Time as _Time, Vote as _Vote } from "./declarations/dao_backend.did.d.ts";
export class Dao_backend implements dao_backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>){}
    async createProposal(arg0: ProposalKind): Promise<Result_1> {
        const result = await this.actor.createProposal(to_candid_ProposalKind_n1(arg0));
        return from_candid_Result_1_n10(result);
    }
    async getMembers(): Promise<Array<Member>> {
        const result = await this.actor.getMembers();
        return result;
    }
    async getPdsCanisterId(): Promise<Principal | null> {
        const result = await this.actor.getPdsCanisterId();
        return from_candid_opt_n12(result);
    }
    async getProposal(arg0: bigint): Promise<ProposalDetail | null> {
        const result = await this.actor.getProposal(arg0);
        return from_candid_opt_n13(result);
    }
    async getProposals(arg0: bigint, arg1: bigint): Promise<PagedResult> {
        const result = await this.actor.getProposals(arg0, arg1);
        return from_candid_PagedResult_n23(result);
    }
    async getVote(arg0: bigint, arg1: Principal): Promise<Vote | null> {
        const result = await this.actor.getVote(arg0, arg1);
        return from_candid_opt_n26(result);
    }
    async vote(arg0: bigint, arg1: boolean): Promise<Result> {
        const result = await this.actor.vote(arg0, arg1);
        return from_candid_Result_n29(result);
    }
}
function from_candid_PagedResult_n23(value: _PagedResult): PagedResult {
    return from_candid_record_n24(value);
}
function from_candid_ProposalDetail_n14(value: _ProposalDetail): ProposalDetail {
    return from_candid_record_n15(value);
}
function from_candid_ProposalStatus_n16(value: _ProposalStatus): ProposalStatus {
    return from_candid_variant_n17(value);
}
function from_candid_Result_1_n10(value: _Result_1): Result_1 {
    return from_candid_variant_n11(value);
}
function from_candid_Result_n29(value: _Result): Result {
    return from_candid_variant_n30(value);
}
function from_candid_Vote_n27(value: _Vote): Vote {
    return from_candid_record_n28(value);
}
function from_candid_opt_n12(value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(value: [] | [_ProposalDetail]): ProposalDetail | null {
    return value.length === 0 ? null : from_candid_ProposalDetail_n14(value[0]);
}
function from_candid_opt_n19(value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(value: [] | [_Vote]): Vote | null {
    return value.length === 0 ? null : from_candid_Vote_n27(value[0]);
}
function from_candid_record_n15(value: {
    id: bigint;
    status: _ProposalStatus;
    title: string;
    votesAgainst: bigint;
    timeStart: bigint;
    votesFor: bigint;
    totalVotingPower: bigint;
    description: string;
    timeEnd: [] | [bigint];
}): {
    id: bigint;
    status: ProposalStatus;
    title: string;
    votesAgainst: bigint;
    timeStart: bigint;
    votesFor: bigint;
    totalVotingPower: bigint;
    description: string;
    timeEnd?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ProposalStatus_n16(value.status),
        title: value.title,
        votesAgainst: value.votesAgainst,
        timeStart: value.timeStart,
        votesFor: value.votesFor,
        totalVotingPower: value.totalVotingPower,
        description: value.description,
        timeEnd: record_opt_to_undefined(from_candid_opt_n22(value.timeEnd))
    };
}
function from_candid_record_n18(value: {
    executingTime: _Time;
    error: string;
    failedTime: _Time;
    choice: [] | [boolean];
}): {
    executingTime: Time;
    error: string;
    failedTime: Time;
    choice?: boolean;
} {
    return {
        executingTime: value.executingTime,
        error: value.error,
        failedTime: value.failedTime,
        choice: record_opt_to_undefined(from_candid_opt_n19(value.choice))
    };
}
function from_candid_record_n20(value: {
    executingTime: _Time;
    choice: [] | [boolean];
}): {
    executingTime: Time;
    choice?: boolean;
} {
    return {
        executingTime: value.executingTime,
        choice: record_opt_to_undefined(from_candid_opt_n19(value.choice))
    };
}
function from_candid_record_n21(value: {
    executingTime: _Time;
    choice: [] | [boolean];
    executedTime: _Time;
}): {
    executingTime: Time;
    choice?: boolean;
    executedTime: Time;
} {
    return {
        executingTime: value.executingTime,
        choice: record_opt_to_undefined(from_candid_opt_n19(value.choice)),
        executedTime: value.executedTime
    };
}
function from_candid_record_n24(value: {
    data: Array<_ProposalDetail>;
    count: bigint;
    totalCount: bigint;
    offset: bigint;
}): {
    data: Array<ProposalDetail>;
    count: bigint;
    totalCount: bigint;
    offset: bigint;
} {
    return {
        data: from_candid_vec_n25(value.data),
        count: value.count,
        totalCount: value.totalCount,
        offset: value.offset
    };
}
function from_candid_record_n28(value: {
    votingPower: bigint;
    choice: [] | [boolean];
}): {
    votingPower: bigint;
    choice?: boolean;
} {
    return {
        votingPower: value.votingPower,
        choice: record_opt_to_undefined(from_candid_opt_n19(value.choice))
    };
}
function from_candid_variant_n11(value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n17(value: {
    failedToExecute: {
        executingTime: _Time;
        error: string;
        failedTime: _Time;
        choice: [] | [boolean];
    };
} | {
    open: null;
} | {
    executing: {
        executingTime: _Time;
        choice: [] | [boolean];
    };
} | {
    executed: {
        executingTime: _Time;
        choice: [] | [boolean];
        executedTime: _Time;
    };
}): {
    __kind__: "failedToExecute";
    failedToExecute: {
        executingTime: Time;
        error: string;
        failedTime: Time;
        choice?: boolean;
    };
} | {
    __kind__: "open";
    open: null;
} | {
    __kind__: "executing";
    executing: {
        executingTime: Time;
        choice?: boolean;
    };
} | {
    __kind__: "executed";
    executed: {
        executingTime: Time;
        choice?: boolean;
        executedTime: Time;
    };
} {
    return "failedToExecute" in value ? {
        __kind__: "failedToExecute",
        failedToExecute: from_candid_record_n18(value.failedToExecute)
    } : "open" in value ? {
        __kind__: "open",
        open: value.open
    } : "executing" in value ? {
        __kind__: "executing",
        executing: from_candid_record_n20(value.executing)
    } : "executed" in value ? {
        __kind__: "executed",
        executed: from_candid_record_n21(value.executed)
    } : value;
}
function from_candid_variant_n30(value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n25(value: Array<_ProposalDetail>): Array<ProposalDetail> {
    return value.map((x)=>from_candid_ProposalDetail_n14(x));
}
function to_candid_InitializeOptions_n6(value: InitializeOptions): _InitializeOptions {
    return to_candid_record_n7(value);
}
function to_candid_InstallAndInitializeOptions_n8(value: InstallAndInitializeOptions): _InstallAndInitializeOptions {
    return to_candid_record_n9(value);
}
function to_candid_ProposalData__1_n3(value: ProposalData__1): _ProposalData__1 {
    return to_candid_record_n4(value);
}
function to_candid_ProposalKind_n1(value: ProposalKind): _ProposalKind {
    return to_candid_variant_n2(value);
}
function to_candid_record_n4(value: {
    id: Principal;
    kind: {
        __kind__: "set";
        set: null;
    } | {
        __kind__: "installAndInitialize";
        installAndInitialize: InstallAndInitializeOptions;
    } | {
        __kind__: "initialize";
        initialize: InitializeOptions;
    };
}): {
    id: Principal;
    kind: {
        set: null;
    } | {
        installAndInitialize: _InstallAndInitializeOptions;
    } | {
        initialize: _InitializeOptions;
    };
} {
    return {
        id: value.id,
        kind: to_candid_variant_n5(value.kind)
    };
}
function to_candid_record_n7(value: {
    hostname: string;
    serviceSubdomain?: string;
    plcIdentifier: string;
}): {
    hostname: string;
    serviceSubdomain: [] | [string];
    plcIdentifier: string;
} {
    return {
        hostname: value.hostname,
        serviceSubdomain: value.serviceSubdomain ? candid_some(value.serviceSubdomain) : candid_none(),
        plcIdentifier: value.plcIdentifier
    };
}
function to_candid_record_n9(value: {
    initializeOptions: InitializeOptions;
    initArgs: Uint8Array;
    wasmModule: Uint8Array;
}): {
    initializeOptions: _InitializeOptions;
    initArgs: Uint8Array;
    wasmModule: Uint8Array;
} {
    return {
        initializeOptions: to_candid_InitializeOptions_n6(value.initializeOptions),
        initArgs: value.initArgs,
        wasmModule: value.wasmModule
    };
}
function to_candid_variant_n2(value: {
    __kind__: "setPdsCanister";
    setPdsCanister: ProposalData__1;
} | {
    __kind__: "postToBluesky";
    postToBluesky: ProposalData;
}): {
    setPdsCanister: _ProposalData__1;
} | {
    postToBluesky: _ProposalData;
} {
    return value.__kind__ === "setPdsCanister" ? {
        setPdsCanister: to_candid_ProposalData__1_n3(value.setPdsCanister)
    } : value.__kind__ === "postToBluesky" ? {
        postToBluesky: value.postToBluesky
    } : value;
}
function to_candid_variant_n5(value: {
    __kind__: "set";
    set: null;
} | {
    __kind__: "installAndInitialize";
    installAndInitialize: InstallAndInitializeOptions;
} | {
    __kind__: "initialize";
    initialize: InitializeOptions;
}): {
    set: null;
} | {
    installAndInitialize: _InstallAndInitializeOptions;
} | {
    initialize: _InitializeOptions;
} {
    return value.__kind__ === "set" ? {
        set: value.set
    } : value.__kind__ === "installAndInitialize" ? {
        installAndInitialize: to_candid_InstallAndInitializeOptions_n8(value.installAndInitialize)
    } : value.__kind__ === "initialize" ? {
        initialize: to_candid_InitializeOptions_n6(value.initialize)
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
}
export function createActor(canisterId: string, options: CreateActorOptions = {}): Dao_backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Dao_backend(actor);
}
