/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddWasmChunkRequest {
  'wasmHash' : Uint8Array,
  'chunk' : Uint8Array,
  'index' : bigint,
}
export interface Dao {
  'addMember' : ActorMethod<[Principal], Result>,
  'addWasmChunk' : ActorMethod<[AddWasmChunkRequest], Result>,
  'createProposal' : ActorMethod<[ProposalKind], Result_1>,
  'finalizeWasmChunks' : ActorMethod<[Uint8Array], Result>,
  'getDelegates' : ActorMethod<[], Array<Delegate>>,
  'getMember' : ActorMethod<[Principal], [] | [Member]>,
  'getMembers' : ActorMethod<[], Array<Member>>,
  'getPdsCanisterId' : ActorMethod<[], [] | [Principal]>,
  'getProposal' : ActorMethod<[bigint], [] | [ProposalDetail]>,
  'getProposals' : ActorMethod<[bigint, bigint], GetProposalsResponse>,
  'getVote' : ActorMethod<[bigint, Principal], [] | [Vote]>,
  'getWasmHashes' : ActorMethod<[], Array<string>>,
  'icrc120_get_events' : ActorMethod<
    [ICRC120GetEventsFilter],
    Array<ICRC120OrchestrationEvent>
  >,
  'removeMember' : ActorMethod<[Principal], Result>,
  'vote' : ActorMethod<[bigint, boolean], Result>,
}
export interface Delegate { 'id' : Principal, 'permissions' : Permissions }
export interface GetEventsFilter {
  'event_types' : [] | [Array<OrchestrationEventType>],
  'end_time' : [] | [bigint],
  'start_time' : [] | [bigint],
  'canister' : [] | [Principal],
}
export interface GetProposalsResponse {
  'data' : Array<ProposalDetail>,
  'count' : bigint,
  'totalCount' : bigint,
  'offset' : bigint,
}
export interface ICRC120GetEventsFilter {
  'prev' : [] | [Uint8Array],
  'take' : [] | [bigint],
  'filter' : [] | [GetEventsFilter],
}
export interface ICRC120OrchestrationEvent {
  'id' : bigint,
  'canister_id' : Principal,
  'timestamp' : bigint,
  'details' : ICRC16,
  'event_type' : OrchestrationEventType,
}
export type ICRC16 = { 'Int' : bigint } |
  { 'Map' : Array<[string, ICRC16]> } |
  { 'Nat' : bigint } |
  { 'Set' : Array<ICRC16> } |
  { 'Nat16' : number } |
  { 'Nat32' : number } |
  { 'Nat64' : bigint } |
  { 'Blob' : Uint8Array } |
  { 'Bool' : boolean } |
  { 'Int8' : number } |
  { 'Nat8' : number } |
  { 'Nats' : Array<bigint> } |
  { 'Text' : string } |
  { 'Bytes' : Uint8Array } |
  { 'Int16' : number } |
  { 'Int32' : number } |
  { 'Int64' : bigint } |
  { 'Option' : [] | [ICRC16] } |
  { 'Floats' : Array<number> } |
  { 'Float' : number } |
  { 'Principal' : Principal } |
  { 'Array' : Array<ICRC16> } |
  { 'ValueMap' : Array<[ICRC16, ICRC16]> } |
  { 'Class' : Array<ICRC16Property> };
export interface ICRC16Property {
  'value' : ICRC16,
  'name' : string,
  'immutable' : boolean,
}
export type LogVisibility = { 'controllers' : null } |
  { 'allowedViewers' : Array<Principal> } |
  { 'public' : null };
export interface Member { 'id' : Principal, 'votingPower' : bigint }
export interface NewCanisterSettings {
  'controllers' : [] | [Array<Principal>],
  'freezingThreshold' : [] | [bigint],
  'wasmMemoryLimit' : [] | [bigint],
  'logVisibility' : [] | [LogVisibility],
  'memoryAllocation' : [] | [bigint],
  'computeAllocation' : [] | [bigint],
  'wasmMemoryThreshold' : [] | [bigint],
  'reservedCyclesLimit' : [] | [bigint],
}
export type OrchestrationEventType = { 'upgrade_initiated' : null } |
  { 'snapshot_requested' : null } |
  { 'snapshot_revert_requested' : null } |
  { 'snapshot_cleaned' : null } |
  { 'upgrade_finished' : null } |
  { 'configuration_changed' : null } |
  { 'snapshot_reverted' : null } |
  { 'canister_started' : null } |
  { 'snapshot_created' : null } |
  { 'canister_stopped' : null };
export interface Permissions {
  'createRecord' : boolean,
  'deleteRecord' : boolean,
  'readLogs' : boolean,
  'putRecord' : boolean,
  'deleteLogs' : boolean,
  'modifyOwner' : boolean,
}
export interface ProposalData {
  'method' : string,
  'args' : { 'raw' : Uint8Array } |
    { 'candidText' : string },
  'canisterId' : Principal,
}
export interface ProposalData__1 {
  'initArgs' : { 'raw' : Uint8Array } |
    { 'candidText' : string },
  'wasmHash' : Uint8Array,
  'kind' : { 'reinstall' : { 'canisterId' : Principal } } |
    {
      'upgrade' : {
        'skipPreUpgrade' : boolean,
        'wasmMemoryPersistence' : { 'keep' : null } |
          { 'replace' : null },
        'canisterId' : Principal,
      }
    } |
    {
      'install' : {
        'kind' : { 'existingCanister' : Principal } |
          {
            'newCanister' : {
              'initialCycleBalance' : bigint,
              'settings' : NewCanisterSettings,
            }
          },
      }
    },
}
export interface ProposalData__2 { 'message' : string }
export interface ProposalData__3 {
  'permissions' : Permissions,
  'delegateId' : Principal,
}
export interface ProposalData__4 { 'canisterId' : Principal }
export interface ProposalDetail {
  'id' : bigint,
  'status' : ProposalStatus,
  'title' : string,
  'votesAgainst' : bigint,
  'timeStart' : bigint,
  'votesFor' : bigint,
  'totalVotingPower' : bigint,
  'description' : string,
  'timeEnd' : [] | [bigint],
}
export type ProposalKind = { 'installPds' : ProposalData__1 } |
  { 'setDelegatePermissions' : ProposalData__3 } |
  { 'setPdsCanister' : ProposalData__4 } |
  { 'postToBluesky' : ProposalData__2 } |
  { 'customCall' : ProposalData };
export type ProposalStatus = {
    'failedToExecute' : {
      'executingTime' : Time,
      'error' : string,
      'failedTime' : Time,
      'choice' : [] | [boolean],
    }
  } |
  { 'open' : null } |
  { 'executing' : { 'executingTime' : Time, 'choice' : [] | [boolean] } } |
  {
    'executed' : {
      'executingTime' : Time,
      'choice' : [] | [boolean],
      'executedTime' : Time,
    }
  };
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : bigint } |
  { 'err' : string };
export type Time = bigint;
export interface Vote { 'votingPower' : bigint, 'choice' : [] | [boolean] }
export interface _SERVICE extends Dao {}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];